In [8]:

from omnireader import Omniwebreader
import pandas as pd
import numpy as np

# Initialize the class
reader = Omniwebreader()

print("Check out which number corresponds to which variable.")
reader.variables_info()
var = [3, 8] # Pull Bartels rotation number and the scalar B


Check out which number corresponds to which variable.
0 : YEAR
1 : DOY
2 : Hour
3 : Bartels rotation number
4 : ID for IMF spacecraft
5 : ID for SW Plasma spacecraft
6 : # of points in IMF averages
7 : # of points in Plasma averag.
8 : Scalar B, nT
9 : Vector B Magnitude,nT
10 : Lat. Angle of B (GSE)
11 : Long. Angle of B (GSE)
12 : BX, nT (GSE, GSM)
13 : BY, nT (GSE)
14 : BZ, nT (GSE)
15 : BY, nT (GSM)
16 : BZ, nT (GSM)
17 : RMS_magnitude, nT
18 : RMS_field_vector, nT
19 : RMS_BX_GSE, nT
20 : RMS_BY_GSE, nT
21 : RMS_BZ_GSE, nT
22 : SW Plasma Temperature, K
23 : SW Proton Density, N/cm^3
24 : SW Plasma Speed, km/s
25 : SW Plasma flow long. angle
26 : SW Plasma flow lat. angle
27 : Alpha/Prot. ratio
28 : Flow pressure
29 : sigma-T,K
30 : sigma-n, N/cm^3)
31 : sigma-V, km/s
32 : sigma-phi V, degrees
33 : sigma-theta V, degrees
34 : sigma-ratio
35 : E elecrtric field
36 : Plasma beta
37 : Alfen mach number
38 : Kp index
39 : R (Sunspot No.)
40 : Dst-index, nT
41 : AE-index, nT
42 : Proton

In [9]:
pdout = "pandas_out"
reader.fetch_to_file(start=20170101,stop=20170102,variables=var,output_file=pdout, style="pandas")
print("Reading the pandas output...")
df = pd.read_csv(pdout + ".lst", delim_whitespace=True)
print(df.head())


Reading the pandas output...
   YEAR  DOY  HR     1    2
0  2017    1   0  2502  7.1
1  2017    1   1  2502  6.5
2  2017    1   2  2502  5.8
3  2017    1   3  2502  6.2
4  2017    1   4  2502  6.7


In [10]:
npout = "numpy_out"
reader.fetch_to_file(start=20170101,stop=20170102,variables=var,output_file=npout, style="numpy")
print("Reading the numpy output...")
a = np.loadtxt(npout + ".lst")
print(a)






Reading the numpy output...
[[2.017e+03 1.000e+00 0.000e+00 2.502e+03 7.100e+00]
 [2.017e+03 1.000e+00 1.000e+00 2.502e+03 6.500e+00]
 [2.017e+03 1.000e+00 2.000e+00 2.502e+03 5.800e+00]
 [2.017e+03 1.000e+00 3.000e+00 2.502e+03 6.200e+00]
 [2.017e+03 1.000e+00 4.000e+00 2.502e+03 6.700e+00]
 [2.017e+03 1.000e+00 5.000e+00 2.502e+03 5.600e+00]
 [2.017e+03 1.000e+00 6.000e+00 2.502e+03 5.000e+00]
 [2.017e+03 1.000e+00 7.000e+00 2.502e+03 4.500e+00]
 [2.017e+03 1.000e+00 8.000e+00 2.502e+03 5.100e+00]
 [2.017e+03 1.000e+00 9.000e+00 2.502e+03 3.400e+00]
 [2.017e+03 1.000e+00 1.000e+01 2.502e+03 4.000e+00]
 [2.017e+03 1.000e+00 1.100e+01 2.502e+03 4.900e+00]
 [2.017e+03 1.000e+00 1.200e+01 2.502e+03 4.200e+00]
 [2.017e+03 1.000e+00 1.300e+01 2.502e+03 3.700e+00]
 [2.017e+03 1.000e+00 1.400e+01 2.502e+03 4.700e+00]
 [2.017e+03 1.000e+00 1.500e+01 2.502e+03 4.600e+00]
 [2.017e+03 1.000e+00 1.600e+01 2.502e+03 4.100e+00]
 [2.017e+03 1.000e+00 1.700e+01 2.502e+03 3.700e+00]
 [2.017e+03 1.000e